import streamlit as st
import pandas as pd


# -----------------------------
# PAGE SETTINGS
# -----------------------------
st.set_page_config(
    page_title="AI Career Comeback",
    page_icon="🌸",
    layout="wide"
)


# -----------------------------
# LOAD DATASET
# -----------------------------
df = pd.read_csv("carrer_data.csv")


# -----------------------------
# TITLE
# -----------------------------
st.title("🌸 AI Career Comeback")
st.subheader("AI-Based Career Recommendation System")

st.write(
    "This application recommends suitable career paths "
    "based on candidate information, skills and interests."
)


# -----------------------------
# DATASET INFORMATION
# -----------------------------
st.divider()

st.header("📊 Dataset Information")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Total Candidates", df.shape[0])

with col2:
    st.metric("Total Features", df.shape[1])

with col3:
    st.metric(
        "Career Options",
        df["Recommended_Career"].nunique()
    )


# -----------------------------
# DATASET PREVIEW
# -----------------------------
st.subheader("🔍 Dataset Preview")

st.dataframe(
    df.head(10),
    use_container_width=True
)
# -----------------------------
# USER PROFILE
# -----------------------------
st.divider()

st.header("👩 Enter Your Profile")

name = st.text_input("Candidate Name")

age = st.number_input(
    "Age",
    min_value=18,
    max_value=60,
    value=25
)

education_options = sorted(
    df["Education"].dropna().unique().tolist()
)

education = st.selectbox(
    "Education",
    education_options
)

skills = st.text_input(
    "Skills",
    placeholder="Example: Python, SQL, Excel"
)

interests = st.text_input(
    "Interests",
    placeholder="Example: Technology, Data Science"
)

st.write("")

analyze = st.button(
    "🚀 Analyze My Career",
    type="primary"
)
# -----------------------------
# AI CAREER RECOMMENDATION
# -----------------------------
if analyze:

    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity

    # Check user input
    if name.strip() == "":
        st.warning("Please enter your name.")

    elif skills.strip() == "":
        st.warning("Please enter your skills.")

    elif interests.strip() == "":
        st.warning("Please enter your interests.")

    else:

        # -----------------------------
        # PREPARE DATASET TEXT
        # -----------------------------
        df["combined_text"] = (
            df["Education"].fillna("").astype(str) + " " +
            df["Skills"].fillna("").astype(str) + " " +
            df["Interests"].fillna("").astype(str)
        ).str.lower()

        # -----------------------------
        # USER PROFILE TEXT
        # -----------------------------
        user_profile = (
            education + " " +
            skills + " " +
            interests
        ).lower()

        # -----------------------------
        # TF-IDF
        # -----------------------------
        vectorizer = TfidfVectorizer()

        all_text = df["combined_text"].tolist()
        all_text.append(user_profile)

        tfidf_matrix = vectorizer.fit_transform(all_text)

        # -----------------------------
        # COSINE SIMILARITY
        # -----------------------------
        user_vector = tfidf_matrix[-1]

        dataset_vectors = tfidf_matrix[:-1]

        similarity_scores = cosine_similarity(
            user_vector,
            dataset_vectors
        )[0]

        # -----------------------------
        # FIND BEST MATCH
        # -----------------------------
        best_index = similarity_scores.argmax()

        recommended_career = df.iloc[
            best_index
        ]["Recommended_Career"]

        similarity_score = similarity_scores[
            best_index
        ]

        recommendation_percentage = round(
            similarity_score * 100,
            2
        )

        # -----------------------------
        # RESULT
        # -----------------------------
        st.divider()

        st.header("🤖 AI Career Recommendation")

        st.success(
            f"🎯 Recommended Career: **{recommended_career}**"
        )

        st.metric(
            "📊 Profile Similarity",
            f"{recommendation_percentage}%"
        )

        st.info(
            "The recommendation is generated by comparing "
            "your education, skills and interests with the "
            "profiles available in the dataset using TF-IDF "
            "and Cosine Similarity."
        ) # -----------------------------
        # TOP 3 CAREER RECOMMENDATIONS
        # -----------------------------
        st.subheader("🏆 Top Career Recommendations")

        result_df = df.copy()

        result_df["Similarity"] = similarity_scores

        # Calculate average similarity for each career
        career_scores = (
            result_df
            .groupby("Recommended_Career")["Similarity"]
            .mean()
            .sort_values(ascending=False)
            .head(3)
        )

        for career, score in career_scores.items():

            percentage = round(
                score * 100,
                2
            )

            st.write(
                f"**{career}** — {percentage}% profile similarity"
            )
        # -----------------------------
        # DATASET RECOMMENDATION SCORE
        # -----------------------------
        st.subheader("📈 Dataset Recommendation Score")

        career_score_data = (
            df.groupby("Recommended_Career")["Recommendation_Score"]
            .mean()
            .sort_values(ascending=False)
        )

        selected_score = career_score_data.get(
            recommended_career,
            0
        )

        st.metric(
            "🎯 Recommended Career Score",
            f"{selected_score:.2f}"
        )

        st.write(
            "This score represents the average Recommendation Score "
            "available for the recommended career in our dataset."
        )# -----------------------------
        # SKILL GAP ANALYSIS
        # -----------------------------
        st.divider()

        st.header("🧩 Skill Gap Analysis")

        # Get skills related to recommended career
        career_rows = df[
            df["Recommended_Career"] == recommended_career
        ]

        dataset_skills = set()

        for skill_text in career_rows["Skills"].dropna():

            skills_list = str(skill_text).lower().split(";")

            for skill in skills_list:
                skill = skill.strip()

                if skill:
                    dataset_skills.add(skill)

        # User skills
        user_skills = set(
            skill.strip().lower()
            for skill in skills.split(",")
            if skill.strip()
        )

        matching_skills = (
            user_skills.intersection(dataset_skills)
        )

        missing_skills = (
            dataset_skills - user_skills
        )

        col1, col2 = st.columns(2)

        with col1:
            st.subheader("✅ Skills You Have")

            if matching_skills:
                for skill in sorted(matching_skills):
                    st.write(f"✓ {skill.title()}")
            else:
                st.info("No direct matching skills found.")

        with col2:
            st.subheader("📚 Skills to Improve")

            if missing_skills:
                for skill in sorted(missing_skills):
                    st.write(f"• {skill.title()}")
            else:
                st.success(
                    "Excellent! You match the available skills."
                )
        # -----------------------------
        # PERSONALIZED CAREER ROADMAP
        # -----------------------------
        st.divider()

        st.header("🗓️ Personalized Career Roadmap")

        st.write(
            f"Your recommended career is **{recommended_career}**. "
            "Follow these steps to prepare for your career comeback:"
        )

        roadmap = [
            "1️⃣ Strengthen your existing skills",
            "2️⃣ Learn the missing skills identified above",
            "3️⃣ Practice with real-world projects",
            "4️⃣ Build a strong project portfolio",
            "5️⃣ Update your resume with recent skills and projects",
            "6️⃣ Prepare for technical and HR interviews",
            "7️⃣ Create or update your professional profile",
            "8️⃣ Start applying for suitable job opportunities"
        ]

        for step in roadmap:
            st.write(step)

        st.success(
            "🌸 Keep learning consistently and build practical "
            "projects to make your career comeback stronger!"
        )     # -----------------------------
        # DOWNLOAD CAREER REPORT
        # -----------------------------
        st.divider()
        
        st.header("📄 Download Career Report")
        
        report = f"""
        AI CAREER COMEBACK REPORT
        =========================
        
        Name: {name}
        Age: {age}
        Education: {education}
        
        TARGET CAREER
        -------------
        {recommended_career}
        
        PROFILE SIMILARITY
        ------------------
        {recommendation_percentage}%
        
        DATASET RECOMMENDATION SCORE
        ----------------------------
           
        {selected_score:.2f}
        
        SKILLS YOU HAVE
        ---------------
          
          {", ".join(sorted(matching_skills)) if matching_skills else "None"}
        
        SKILLS TO IMPROVE
        -----------------
          {", ".join(sorted(missing_skills)) if missing_skills else "None"}
        
        CAREER ROADMAP
        --------------
        1. Strengthen existing skills
        2. Learn missing skills
        3. Build real-world projects
        4. Create a project portfolio
        5. Update resume
        6. Prepare for interviews
        7. Update professional profile
        8. Apply for suitable jobs
        
        Generated by AI Career Comeback
        """
        
        st.download_button(
            label="📥 Download My Career Report",
            data=report,
            file_name="AI_Career_Comeback_Report.txt",
            mime="text/plain"
        )   
        # -----------------------------
        # WHY THIS CAREER?
        # -----------------------------
        st.divider()

        st.header("💡 Why This Career?")

        st.write(
        f"Your profile is most similar to the **{recommended_career}** "
        "career based on your education, skills and interests."
        )

        st.write(
        f"Your profile similarity score is **{recommendation_percentage}%**."
        )

        if matching_skills:
         st.write(
        "Your matching skills include: "
        + ", ".join(
            skill.title() for skill in sorted(matching_skills)
        )
        + "."
        )

        if missing_skills:
            st.write(
            "To improve your suitability, focus on learning: "
            + ", ".join(
            skill.title() for skill in sorted(missing_skills)
            )
            + "."
            )

        st.success(
        "🌸 Keep improving your skills and build practical projects "
        "to strengthen your career comeback."
            )